/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Carolina
 */
public class telaDadosDoTitulo extends javax.swing.JFrame {
        String NumeroDoDocumento; 
        String NossoNumero;
        String DataDoDocumento;
        String TipoDoDocumento;
        String Desconto;
        String Mora;
        String DigitoDoNossoNumero;
        String DataDoVencimento;
        String Aceite;
        String Deducao;
        String Valor;
        String ValorCobrado;
        String Acrescimo;
        
    public telaDadosDoTitulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        NumeroDoDocumentoTitulo = new javax.swing.JTextField();
        NossoNumeroTitulo = new javax.swing.JTextField();
        DigitoDoNossoNumeroTitulo = new javax.swing.JTextField();
        ValorTitulo = new javax.swing.JTextField();
        TipoDoDocumentoTitulo = new javax.swing.JTextField();
        AceiteTitulo = new javax.swing.JTextField();
        DescontoTitulo = new javax.swing.JTextField();
        DeducaoTitulo = new javax.swing.JTextField();
        MoraTitulo = new javax.swing.JTextField();
        ValorCobradoTitulo = new javax.swing.JTextField();
        AcrescimoTitulo = new javax.swing.JTextField();
        DataDoDocumentoTitulo = new javax.swing.JFormattedTextField();
        DataDoVencimentoTitulo = new javax.swing.JFormattedTextField();
        Voltar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Dados do Titulo ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(276, 6, 140, 14);

        jLabel2.setText("Numero do documento: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 30, 140, 20);

        jLabel3.setText("Nosso numero: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 70, 120, 14);

        jLabel4.setText("Digito do nosso numero:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 70, 150, 14);

        jLabel5.setText("Valor:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(470, 80, 50, 14);

        jLabel6.setText("Data do documento:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 110, 130, 14);

        jLabel7.setText("Data do vencimento:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(190, 110, 150, 14);

        jLabel8.setText("Tipo do documento:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 150, 130, 14);

        jLabel9.setText("Aceite:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 150, 80, 14);

        jLabel10.setText("Desconto:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(90, 230, 80, 14);

        jLabel11.setText("Deduçao:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 230, 80, 14);

        jLabel12.setText("Mora:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(100, 274, 70, 20);

        jLabel13.setText("Acréscimo:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(460, 180, 80, 14);

        jLabel14.setText("Valor cobrado: ");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(450, 130, 90, 14);

        NumeroDoDocumentoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroDoDocumentoTituloActionPerformed(evt);
            }
        });
        getContentPane().add(NumeroDoDocumentoTitulo);
        NumeroDoDocumentoTitulo.setBounds(60, 50, 115, 20);
        getContentPane().add(NossoNumeroTitulo);
        NossoNumeroTitulo.setBounds(60, 90, 115, 20);
        getContentPane().add(DigitoDoNossoNumeroTitulo);
        DigitoDoNossoNumeroTitulo.setBounds(200, 90, 60, 20);

        ValorTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorTituloActionPerformed(evt);
            }
        });
        getContentPane().add(ValorTitulo);
        ValorTitulo.setBounds(440, 100, 96, 20);

        TipoDoDocumentoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoDoDocumentoTituloActionPerformed(evt);
            }
        });
        getContentPane().add(TipoDoDocumentoTitulo);
        TipoDoDocumentoTitulo.setBounds(60, 170, 114, 20);
        getContentPane().add(AceiteTitulo);
        AceiteTitulo.setBounds(190, 170, 120, 20);
        getContentPane().add(DescontoTitulo);
        DescontoTitulo.setBounds(70, 250, 96, 20);
        getContentPane().add(DeducaoTitulo);
        DeducaoTitulo.setBounds(180, 250, 96, 20);
        getContentPane().add(MoraTitulo);
        MoraTitulo.setBounds(70, 300, 96, 20);
        getContentPane().add(ValorCobradoTitulo);
        ValorCobradoTitulo.setBounds(440, 150, 96, 20);
        getContentPane().add(AcrescimoTitulo);
        AcrescimoTitulo.setBounds(445, 197, 96, 20);
        getContentPane().add(DataDoDocumentoTitulo);
        DataDoDocumentoTitulo.setBounds(60, 130, 113, 20);
        getContentPane().add(DataDoVencimentoTitulo);
        DataDoVencimentoTitulo.setBounds(180, 130, 116, 20);

        Voltar.setText("Voltar");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(410, 300, 70, 23);

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(313, 300, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NumeroDoDocumentoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroDoDocumentoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroDoDocumentoTituloActionPerformed

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
      
         this.dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void TipoDoDocumentoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoDoDocumentoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TipoDoDocumentoTituloActionPerformed

    private void ValorTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorTituloActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NumeroDoDocumento = NumeroDoDocumentoTitulo.getText();
        NossoNumero = NossoNumeroTitulo.getText();
        DigitoDoNossoNumero = DigitoDoNossoNumeroTitulo.getText();
        DataDoDocumento = DataDoDocumentoTitulo.getText();
        DataDoVencimento = DataDoVencimentoTitulo.getText();
        TipoDoDocumento = TipoDoDocumentoTitulo.getText();
        Aceite = AceiteTitulo.getText();
        Desconto = DescontoTitulo.getText();
        Deducao = DeducaoTitulo.getText();
        Mora = MoraTitulo.getText();
        Valor = ValorTitulo.getText();
        ValorCobrado=ValorCobradoTitulo.getText();
        Acrescimo=AcrescimoTitulo.getText();
       
                
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaDadosDoTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaDadosDoTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaDadosDoTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaDadosDoTitulo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaDadosDoTitulo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AceiteTitulo;
    private javax.swing.JTextField AcrescimoTitulo;
    private javax.swing.JFormattedTextField DataDoDocumentoTitulo;
    private javax.swing.JFormattedTextField DataDoVencimentoTitulo;
    private javax.swing.JTextField DeducaoTitulo;
    private javax.swing.JTextField DescontoTitulo;
    private javax.swing.JTextField DigitoDoNossoNumeroTitulo;
    private javax.swing.JTextField MoraTitulo;
    private javax.swing.JTextField NossoNumeroTitulo;
    private javax.swing.JTextField NumeroDoDocumentoTitulo;
    private javax.swing.JTextField TipoDoDocumentoTitulo;
    private javax.swing.JTextField ValorCobradoTitulo;
    private javax.swing.JTextField ValorTitulo;
    private javax.swing.JButton Voltar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
