/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Carolina
 */
public class telaDadosDoBoleto extends javax.swing.JFrame {
    String LocalDePagamento;
    String InstrucaoSacado;
    String Instrucao1;
    String Instrucao2;
    String Instrucao3;
    String Instrucao4;
    String Instrucao5;
    String Instrucao6;
    String Instrucao7;
    String Instrucao8;
   
    
    public telaDadosDoBoleto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LocalDePagamentoBoleto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        InstrucaoSacadoBoleto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Instrucao6Boleto = new javax.swing.JTextField();
        Instrucao1Boleto = new javax.swing.JTextField();
        Instrucao2Boleto = new javax.swing.JTextField();
        Instrucao3Boleto = new javax.swing.JTextField();
        Instrucao4Boleto = new javax.swing.JTextField();
        Instrucao5Boleto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Dados do Boleto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 20, 78, 14);

        jLabel2.setText("Local de pagamento: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 70, 120, 14);

        LocalDePagamentoBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocalDePagamentoBoletoActionPerformed(evt);
            }
        });
        getContentPane().add(LocalDePagamentoBoleto);
        LocalDePagamentoBoleto.setBounds(60, 90, 110, 30);

        jLabel3.setText("Instrução ao sacado");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 70, 110, 14);
        getContentPane().add(InstrucaoSacadoBoleto);
        InstrucaoSacadoBoleto.setBounds(200, 90, 110, 30);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(240, 90, 55, 14);

        jLabel11.setText("Instrução 5");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(220, 210, 55, 14);

        jLabel12.setText("Instrução 6");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(350, 210, 55, 14);

        jLabel4.setText("Instrução 2");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 130, 55, 14);

        jLabel5.setText("Instrução 3");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 130, 55, 14);

        jLabel7.setText("Instrução 4");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 210, 55, 14);

        jLabel8.setText("Instrução 1");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 130, 55, 14);
        getContentPane().add(Instrucao6Boleto);
        Instrucao6Boleto.setBounds(330, 230, 110, 50);

        Instrucao1Boleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Instrucao1BoletoActionPerformed(evt);
            }
        });
        getContentPane().add(Instrucao1Boleto);
        Instrucao1Boleto.setBounds(60, 150, 110, 50);
        getContentPane().add(Instrucao2Boleto);
        Instrucao2Boleto.setBounds(200, 150, 110, 50);
        getContentPane().add(Instrucao3Boleto);
        Instrucao3Boleto.setBounds(330, 150, 110, 50);

        Instrucao4Boleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Instrucao4BoletoActionPerformed(evt);
            }
        });
        getContentPane().add(Instrucao4Boleto);
        Instrucao4Boleto.setBounds(60, 230, 110, 50);
        getContentPane().add(Instrucao5Boleto);
        Instrucao5Boleto.setBounds(200, 230, 110, 50);

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 320, 110, 23);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 320, 61, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           LocalDePagamento = LocalDePagamentoBoleto.getText();
           InstrucaoSacado = InstrucaoSacadoBoleto.getText();
           Instrucao1 = Instrucao1Boleto.getText();
           Instrucao2 = Instrucao2Boleto.getText();
           Instrucao3 = Instrucao3Boleto.getText();
           Instrucao4 = Instrucao4Boleto.getText();
           Instrucao5 = Instrucao5Boleto.getText();
           Instrucao6 = Instrucao6Boleto.getText();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void LocalDePagamentoBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocalDePagamentoBoletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocalDePagamentoBoletoActionPerformed

    private void Instrucao1BoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Instrucao1BoletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Instrucao1BoletoActionPerformed

    private void Instrucao4BoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Instrucao4BoletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Instrucao4BoletoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaDadosDoBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaDadosDoBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaDadosDoBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaDadosDoBoleto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaDadosDoBoleto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Instrucao1Boleto;
    private javax.swing.JTextField Instrucao2Boleto;
    private javax.swing.JTextField Instrucao3Boleto;
    private javax.swing.JTextField Instrucao4Boleto;
    private javax.swing.JTextField Instrucao5Boleto;
    private javax.swing.JTextField Instrucao6Boleto;
    private javax.swing.JTextField InstrucaoSacadoBoleto;
    private javax.swing.JTextField LocalDePagamentoBoleto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
