/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

/**
 *
 * @author Carolina
 */
public class telaSacado extends javax.swing.JFrame {
    
    String Nome;
    String CPF;
    String Logradouro;
    String Numero;
    String UF;
    String Bairro;
    String CEP;
    String Localidade;
    
    
    
    public telaSacado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        NomeSacado = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        LogradouroSacado = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        NumeroSacado = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        UFSacado = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        CEPSacado = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        BairroSacado = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LocalidadeSacado = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        CPFSacado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel14.setText("Sacado");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(150, 35, 35, 14);

        jLabel15.setText("Nome:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(40, 70, 31, 14);

        NomeSacado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeSacadoActionPerformed(evt);
            }
        });
        getContentPane().add(NomeSacado);
        NomeSacado.setBounds(83, 55, 291, 30);

        jLabel16.setText("CPF:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(42, 96, 23, 14);

        jLabel17.setText("Endereço:");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(120, 120, 52, 14);
        getContentPane().add(LogradouroSacado);
        LogradouroSacado.setBounds(90, 150, 159, 20);

        jLabel21.setText("Nº");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(260, 150, 12, 14);

        NumeroSacado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumeroSacadoActionPerformed(evt);
            }
        });
        getContentPane().add(NumeroSacado);
        NumeroSacado.setBounds(280, 150, 22, 14);

        jLabel18.setText("UF:");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(310, 150, 17, 14);
        getContentPane().add(UFSacado);
        UFSacado.setBounds(330, 150, 40, 20);

        jLabel19.setText("CEP:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(60, 180, 23, 14);

        CEPSacado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CEPSacadoActionPerformed(evt);
            }
        });
        getContentPane().add(CEPSacado);
        CEPSacado.setBounds(90, 180, 157, 20);

        jLabel20.setText("Bairro:");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(260, 180, 32, 14);
        getContentPane().add(BairroSacado);
        BairroSacado.setBounds(300, 180, 85, 20);

        jLabel1.setText("Logradouro:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 150, 70, 20);

        jLabel2.setText("Localidade:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 210, 60, 14);
        getContentPane().add(LocalidadeSacado);
        LocalidadeSacado.setBounds(90, 210, 160, 20);

        jButton2.setText("Confirmar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 250, 79, 23);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 250, 61, 23);
        getContentPane().add(CPFSacado);
        CPFSacado.setBounds(90, 90, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeSacadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeSacadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeSacadoActionPerformed

    private void CEPSacadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CEPSacadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CEPSacadoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           Nome = NomeSacado.getText();
           CPF = CPFSacado.getText();
           Logradouro = LogradouroSacado.getText();
           Numero = NumeroSacado.getText();
           UF = UFSacado.getText();
           CEP = CEPSacado.getText();
           Bairro = BairroSacado.getText();
           Localidade = LocalidadeSacado.getText();
           
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NumeroSacadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumeroSacadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumeroSacadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaSacado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaSacado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaSacado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaSacado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaSacado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BairroSacado;
    private javax.swing.JFormattedTextField CEPSacado;
    private javax.swing.JTextField CPFSacado;
    private javax.swing.JTextField LocalidadeSacado;
    private javax.swing.JTextField LogradouroSacado;
    private javax.swing.JTextField NomeSacado;
    private javax.swing.JTextField NumeroSacado;
    private javax.swing.JTextField UFSacado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    // End of variables declaration//GEN-END:variables
}
